### ISSUE TITLE
Initializing Issue

### ISSUE THREAD

**Issue by before30** [kpug/readbook#1]
프로젝트 초기 작업을 위해 협의할 이슈 등록

**Comment by before30** [comment]
Heroku 등록하기

**Comment by looklazy** [comment]
코드 컨벤션 정하기

**Comment by before30** [comment]
CI 등록하기

**Comment by before30** [comment]
코드 커밋 메시지 컨벤션 정하기

**Comment by looklazy** [comment]
Github 설정하기 
- porject
- member
- ...

**Comment by looklazy** [comment]
embedded database 선택하기

**Comment by jayden-17** [comment]
- [x] Heroku 등록하기
- [ ] 코드 컨벤션 정하기
- [ ] 코드 커밋 메시지 컨벤션 정하기
- [ ] CI 등록하기
- [x] Github 설정하기

**Comment by before30** [comment]
이슈 등록에 컨벤션이 있어야할까요?

**Comment by before30** [comment]
마일스톤 정하기

**Comment by before30** [comment]
브랜치 전략

**Comment by pr-lawrence** [comment]
회사에서는 gitflow 를 사용하고 있는데요. 저희는 정기배포가 있다 보니까 이 전략이 잘 맞는데,
이 프로젝트는 gitflow보다는 github flow로 진행하는게 더 적절할 것 같아요.

마스터 프랜치에 보호 설정하고, PR로 머지하는 방식으로 하면 좋겠네요.

**Comment by pr-lawrence** [comment]
Tab 이신가요. space이신가요? 저는 스페이스 성애자입니다.

**Comment by looklazy** [comment]
space 2칸에 한표 던집니다

**Comment by pr-lawrence** [comment]
자바에 스페이스 2칸이라니 ;ㅁ;

**Comment by looklazy** [comment]
Code style: [Redbook Code Style v0.1.xml.zip](https://github.com/kpug/redbook/files/1457414/Redbook.Code.Style.v0.1.xml.zip)

**Comment by jinuk17** [comment]
https://travis-ci.org

**Comment by looklazy** [comment]
Commit message: http://meetup.toast.com/posts/106 
(꼭 따라야할 필요는 없음)

제목과 본문 구분, github의 issue close 기능 정도만 보고 사용하면 되지 않을까요

**Comment by looklazy** [comment]
CI: https://github.com/marketplace/category/continuous-integration
